name: kubeclear-ci

on:
  push:
    branches: 
        - "**" 
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:   
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code  
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-py3.12-${{ hashFiles('poetry.lock', 'pyproject.toml') }}    

      - name: Install dependencies
        run: |
          poetry install --no-root  --no-interaction
      
      - name: Build package (sdist + wheel)
        run: poetry build    

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate 
          poetry run kubeclear --namespace mpe --topology-spread-check --output csv --upgrade-precheck

      - name: Upload coverage & test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-py3.12
          path: |
            coverage.xml
            htmlcov/
            junit.xml
          retention-days: 14

      - name: Upload built package
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/     

          